from functools import lru_cache
from uuid import UUID

from pydantic import PositiveInt
from sqlmodel import Session, col, create_engine, select

from src.config.basic_config import get_config
from src.config.logger import get_logger
from src.models.incident import EventsInIncident, Incident
from src.routes.schemas.incidents import IncidentGet, IncidentQuery

config = get_config()
logger = get_logger(__name__)


class DBClient:
    """Singleton class to manage database read operations."""

    def __init__(self):
        self.engine = create_engine(config.db_url)

    def get_incident_by_id(self, incident_id: PositiveInt) -> IncidentGet | None:
        """Returns the incident with the given ID, or None if not found."""
        with Session(self.engine) as session:
            incident = session.get(Incident, incident_id)
            if incident:
                incident_dict = incident.model_dump()
                incident_id = incident_dict["id"]
                incident_dict["events"] = self._get_events_of_incidents([incident_id])[incident_id]
                return IncidentGet.model_validate(incident_dict)

        return None

    def _get_events_of_incidents(self, incident_ids: list[PositiveInt]) -> dict[PositiveInt, list[UUID]]:
        """Returns a mapping of incident IDs to lists of associated event IDs."""
        with Session(self.engine) as session:
            statement = select(EventsInIncident.incident_id, EventsInIncident.event_id).where(col(EventsInIncident.incident_id).in_(incident_ids))
            results = session.exec(statement).all()

        incident_events_map: dict[PositiveInt, list[UUID]] = {incident_id: [] for incident_id in incident_ids}
        for incident_id, event_id in results:
            incident_events_map[incident_id].append(event_id)

        return incident_events_map

    def get_incidents(self, query: IncidentQuery) -> list[IncidentGet]:
        """Returns a page of incidents matching the provided query."""
        statement = select(Incident)
        if query.service is not None:
            statement = statement.where(Incident.service == query.service)
        if query.environment is not None:
            statement = statement.where(Incident.environment == query.environment)
        if query.status is not None:
            statement = statement.where(Incident.status == query.status)
        if query.start_time_from is not None:
            statement = statement.where(Incident.start_time >= query.start_time_from)
        if query.start_time_to is not None:
            statement = statement.where(Incident.start_time <= query.start_time_to)

        statement = statement.order_by(col(Incident.created_at).desc(), col(Incident.id).desc())
        offset = (query.page - 1) * query.page_size

        with Session(self.engine) as session:
            incidents = list(session.exec(statement.offset(offset).limit(query.page_size)).all())

        incident_ids = [incident.id for incident in incidents]
        incident_event_map = self._get_events_of_incidents(incident_ids)  # type: ignore[arg-type] #incident IDs are autogenerated when created.
        incidents_with_events = []
        for incident in incidents:
            incident_dict = incident.model_dump()
            incident_dict["events"] = incident_event_map[incident.id]  # type: ignore[index] #incident IDs are autogenerated when created.
            incidents_with_events.append(IncidentGet.model_validate(incident_dict))

        return incidents_with_events

    def get_incident_id_for_event(self, event_id: UUID) -> PositiveInt | None:
        """Returns the incident ID associated with the given event ID, or None if not found."""
        with Session(self.engine) as session:
            result = session.exec(select(EventsInIncident.incident_id).where(col(EventsInIncident.event_id) == event_id)).first()
            return result


@lru_cache()
def get_db_client() -> DBClient:
    """Returns a singleton instance of the DBClient."""
    return DBClient()
